import { Header } from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { isLoggedIn } from "@/lib/auth";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await isLoggedIn();

  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <div className="max-w-5xl m-auto w-full px-4">
          {children}
        </div>

      </body>
    </html>
  );
}
